# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='isalive',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='id',
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
