# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20160428_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='first_access',
        ),
        migrations.AddField(
            model_name='computer',
            name='activity',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 1, 0, 0), verbose_name='Latest activity'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
