# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160428_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='activity',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
