# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20160428_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
